### ISSUE TITLE
Rocm docker compose build issue (installs latest pytorch and complains about it).

### ISSUE THREAD

**Issue by TotallyTroll** [ai-dock/fluxgym#1]
Has anybody achieve any luck with rocm option?
I've provided next args / params within docker-compose.yaml:

```
services:
  supervisor:
    platform: linux/amd64
    build:
      context: ./build
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        PYTORCH_VERSION: ${PYTORCH_VERSION:-2.4.1}
        FLUXGYM_BUILD_REF: ${FLUXGYM_BUILD_REF:-e118480}
        IMAGE_BASE: ${IMAGE_BASE:-ghcr.io/ai-dock/python:${PYTHON_VERSION:-3.10}-v2-rocm-6.0-core-22.04}
      tags:
        - "ghcr.io/ai-dock/fluxgym:${IMAGE_TAG:-v2-rocm-6.0-core-22.04}"
        
    image: ghcr.io/ai-dock/fluxgym:${IMAGE_TAG:-v2-rocm-6.0-core-22.04}
    
    devices:
      - "/dev/dri:/dev/dri"
      # For AMD GPU
      - "/dev/kfd:/dev/kfd"
```

Still during _docker compose build_ last script RUN layer next error occurs:

```
56.9 Expected PyTorch 2.4.1 but found 2.7.0+cu126\n
------
failed to solve: process "/bin/bash -c set -eo pipefail && /opt/ai-dock/bin/build/layer1/init.sh | tee -a /var/log/build.log" did not complete successfully: exit code: 1
```

Probably what happens - amd script scenario doesn't follow up PYTORCH_VERSION: ${PYTORCH_VERSION:-2.4.1} at some point, and just installs latest one, which is exactly 2.7 at the moment (and of course cuda version of it).

Any ideas how to fix this?
